language: cpp

# container based has faster start up
sudo: false

dist: trusty

env:
  global:
    - OMP_NUM_THREADS=4

addons:
  apt:
    packages:
      - libgsl0-dev

compiler:
  - gcc

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ./runs_test
